### ISSUE TITLE
Any requisites to run the code?

### ISSUE THREAD

**Issue by hmdliu** [lxlscut/APAP_S#1]
您好！从项目命名来看您应该是国人，所以我就写中文啦。

我是刚刚入坑图像拼接不久的小白，感觉您的代码写得很严谨，所以想尝试跑一下。

请问有哪些依赖库需要提前安装(比如vlfeat，其实我不太懂这些orz)？然后，项目是否需要用特定的IDE打开呢？

打扰啦，多谢！

**Comment by lxlscut** [comment]
项目我是使用使用pychram编写的，然后环境添加vlfeat,numpy,opencv就可以了啦。
vlfeat的话版本支持到python3.6目前。

**Comment by hmdliu** [comment]
好的，谢谢！
