### ISSUE TITLE
环境添加vlfeat的问题

### ISSUE THREAD

**Issue by volcano6322** [lxlscut/APAP_S#2]
您好，我是在win10系统上使用pycharm进行的编译，在尝试添加cyvlfeat的时候采用cmd输入pip install cyvlfeat的方式，但是安装失败，请问有什么方法可以安装cyvlfeat吗？感激不尽！

**Comment by lxlscut** [comment]
现在用oopenc4.5的自带有sift了已经，你可以试试先发自我的华为手机-------- 原始邮件 --------发件人： volcano6322 ***@***.***>日期： 2021年4月21日周三 晚上10:33收件人： lxlscut/APAP_S ***@***.***>抄送： Subscribed ***@***.***>主    题： [lxlscut/APAP_S] 环境添加vlfeat的问题 (#2)

您好，我是在win10系统上使用pycharm进行的编译，在尝试添加cyvlfeat的时候采用cmd输入pip install cyvlfeat的方式，但是安装失败，请问有什么方法可以安装cyvlfeat吗？感激不尽！
