### ISSUE TITLE
关于mesh的问题

### ISSUE THREAD

**Issue by jsjy1** [lxlscut/APAP_S#3]
您好！十分感谢您的代码。
我看您的代码中是对整张画布进行划分网格，然后使用逆向warp得到变换的src图。我看其他人代码好像也是这样做的，
1.这一点我一直不理解原本不是想特征点对图上每个块的影响嘛？这样做的话感觉好别扭，请问有其他的理解方式吗？
2.如果对最后画布进行mesh，假设分成100*100，然后变换后放大很多倍，这样落在src上的网格不就少了嘛？最极限的情况下，应该只能分到一个格子吧。

**Comment by lxlscut** [comment]
第一个的话作者源码就是这样的吧，时间太久了，具体我也忘了。 第二个的话我记得投影时是可以进行线性插值的，这个opencv里面有相应的函数，你自己改改就可以了。
